[tool.poetry]
authors = ["m09 <142691+m09@users.noreply.github.com>"]
classifiers = ["Topic :: Software Development :: Build Tools"]
description = "Tool to handle multiple beamer decks."
homepage = "https://github.com/mlambda/deckz"
license = "Apache-2.0"
name = "deckz"
readme = "README.md"
version = "20.3.1"

[tool.poetry.dependencies]
Jinja2 = "^3" 
PyYAML = "^6" 
appdirs = "^1" 
cyclopts = "^3.1.1" # Should keep minor and patch
email-validator = "^2" 
google-api-python-client = "^2" 
google-auth-oauthlib = "^1" 
matplotlib = "^3" 
pydantic = "^2" 
pygit2 = "^1" 
python = "^3.10" 
rich = "^13" 
sendgrid = "^6" 
typer = "^0.13" 
watchdog = "^6" 

[tool.poetry.group.dev.dependencies]
mkdocs = "*"
mkdocs-gen-files = "*"
mkdocs-literate-nav = "*"
mkdocs-material = "*"
mkdocstrings = {extras = ["python"], version = "*"}
mypy = "*"
"pdfminer.six" = "*"
pytest = "*"
pytest-cov = "*"
ruff = "*"
types-PyYAML = "*"
types-requests = "*"

[tool.poetry.scripts]
deckz = 'deckz.cli:main'

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
ignore = ["D1", "D203", "D213"]
preview = true
select = ["A", "B", "C", "D", "DOC", "E", "EM", "F", "N", "PIE", "PTH", "RET", "RUF", "SIM", "SLF", "UP", "W"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
strict_optional = true

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
