[tool.poetry]
authors = ["m09 <142691+m09@users.noreply.github.com>"]
classifiers = ["Topic :: Software Development :: Build Tools"]
description = "Tool to handle multiple beamer decks."
homepage = "https://github.com/mlambda/deckz"
license = "Apache-2.0"
name = "deckz"
readme = "README.md"
version = "20.2.0"

[tool.poetry.dependencies]
Jinja2 = "^3"
PyYAML = "^6"
appdirs = "^1"
email-validator = "^2"
google-api-python-client = "^2"
google-auth-oauthlib = "^1"
matplotlib = "^3"
pydantic = "^2"
pygit2 = "^1"
python = "^3.10"
rich = "^13"
sendgrid = "^6"
typer = "^0.12"
watchdog = "^4"

[tool.poetry.group.dev.dependencies]
black = "^23"
flake8 = "^6"
flake8-bugbear = "^23"
flake8-new-union-types = "^0.4"
flake8-pep585 = "^0.1"
isort = "^5"
mkdocs = "^1"
mkdocs-gen-files = "^0.4"
mkdocs-literate-nav = "^0.6"
mkdocs-material = "^9"
mkdocstrings = {extras = ["python"], version = "^0.20"}
mypy = "^1"
"pdfminer.six" = "^20221105"
pylint = "^2"
pytest = "^7"
pytest-cov = "^4"
types-PyYAML = "^6"
types-requests = "^2"

[tool.poetry.scripts]
deckz = 'deckz.cli:main'

[tool.isort]
profile = "black"

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
strict_optional = true

[tool.pylint."MASTER"]
jobs = 0
load-plugins = "pylint.extensions.docparams"

[tool.pylint."MESSAGES CONTROL"]
disable = "all"
enable = ["missing-param-doc", "differing-param-doc", "differing-type-doc", "missing-return-doc"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
