[tool.poetry]
authors = ["m09 <142691+m09@users.noreply.github.com>"]
classifiers = ["Topic :: Software Development :: Build Tools"]
description = "Tool to handle multiple beamer decks."
homepage = "https://github.com/mlambda/deckz"
license = "Apache-2.0"
name = "deckz"
readme = "README.md"
version = "20.2.0"

[tool.poetry.dependencies]
Jinja2 = "^3"
PyYAML = "^6"
appdirs = "^1"
email-validator = "^2"
google-api-python-client = "^2"
google-auth-oauthlib = "^1"
matplotlib = "^3"
pydantic = "^2"
pygit2 = "^1"
python = "^3.10"
rich = "^13"
sendgrid = "^6"
typer = "^0.12"
watchdog = "^4"

[tool.poetry.group.dev.dependencies]
black = "*"
flake8 = "*"
flake8-bugbear = "*"
flake8-new-union-types = "*"
flake8-pep585 = "*"
isort = "*"
mkdocs = "*"
mkdocs-gen-files = "*"
mkdocs-literate-nav = "*"
mkdocs-material = "*"
mkdocstrings = {extras = ["python"], version = "*"}
mypy = "*"
"pdfminer.six" = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
types-PyYAML = "*"
types-requests = "*"

[tool.poetry.scripts]
deckz = 'deckz.cli:main'

[tool.isort]
profile = "black"

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
strict_optional = true

[tool.pylint."MASTER"]
jobs = 0
load-plugins = "pylint.extensions.docparams"

[tool.pylint."MESSAGES CONTROL"]
disable = "all"
enable = ["missing-param-doc", "differing-param-doc", "differing-type-doc", "missing-return-doc"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
