name: CD

on:
  push:
    tags:
      - "v*"

jobs:
  deploy-pypi:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Build and deploy on PyPI
        run: |
          export TAG=${GITHUB_REF##*/}
          test $(uv version | cut -f 2 -d " ") == $TAG
          uv build
          uv publish
