name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  style:
    name: Check style conventions and test the package
    runs-on: ubuntu-latest
    container: nzmognzmp/deckz-ci-worker
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install the package
        run: /root/.poetry/bin/poetry install
      - name: Test the package style conventions
        run: /root/.poetry/bin/poetry run make check
      - name: Run the tests
        run: /root/.poetry/bin/poetry run pytest --cov=./ --cov-report=xml
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
