name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style:
    name: Check style conventions and test the package
    runs-on: ubuntu-latest
    container: shuuchuu/deckz-ci:latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install the package
        run: poetry install

      - name: Test the package style conventions
        run: poetry run make check

      - name: Run the tests
        run: poetry run pytest --cov=./ --cov-report=xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          root_dir: ./
          token: ${{ secrets.CODECOV_TOKEN }}
